[project]
name = "connect4"
version = "0.1.0"
description = "Connect4"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.9",
    "scipy>=1.16.2",
    "torch>=2.8.0",
]
