[project]
name = "connect4"
version = "0.1.0"
description = "Connect4"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "pydantic>=2.11.9",
    "scipy>=1.16.2",
    "tensorboard>=2.20.0",
    "torch>=2.8.0",
]
[pyright]